FROM node:20-alpine AS frontend-builder
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app
COPY frontend/neon-hub-config/package.json frontend/neon-hub-config/pnpm-lock.yaml ./
RUN pnpm install
COPY frontend/neon-hub-config .
RUN pnpm build

FROM nginx:stable-alpine-slim

COPY --from=frontend-builder /app/dist /usr/share/nginx/html
COPY frontend/neon-hub-config/nginx.conf /etc/nginx/conf.d/default.conf
