# Build the frontend
version: "3"

tasks:
  sbom:
    desc: Generate a software bill of materials for the project
    cmds:
      - snyk sbom --format spdx2.3+json > sbom.json
      - cd frontend/neon-hub-config
      - snyk sbom --format spdx2.3+json > sbom.json
      - cd ..
  build-fe:
    dir: frontend/neon-hub-config
    desc: Build the frontend
    cmds:
      - pnpm install
      - pnpm run build:py
  fe-dev-server:
    dir: frontend/neon-hub-config
    desc: Start the frontend development server
    cmds:
      - pnpm install
      - pnpm run dev
  py-run:
    desc: Run the python server
    env:
      OVOS_CONFIG_BASE_FOLDER: neon
      OVOS_CONFIG_FILENAME: neon.yaml
    cmds:
      - poetry run python neon_hub_config/main.py
  build-docker:
    desc: Build the production docker image
    cmds:
      - task build-fe
      - docker build -t neon-hub-config .
  docker-run:
    desc: Run the production docker image from a local build
    cmds:
      - docker run -p 80:80 -v ~/.config/neon:/home/neon/.config/neon neon-hub-config
